# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install activesupport
- gem update cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail
- xctool test -workspace Example/ImageColors.xcworkspace -scheme ImageColors-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --no-clean
after_success:
- echo '\ndone!\n'
- gem cocoapod --version
- xctool -version
- xcodebuild -version -sdk